# Site settings
title: Solace Messaging with Pivotal Cloud Foundry
baseurl: "/solace-samples-cloudfoundry-java" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-cloudfoundry-java

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Solace JCSMP and JMS Versions
jcsmp_version: 10.+
jms_version: 10.+

# Links
docs-core-concepts: http://docs.solace.com/Features/Core-Concepts.htm
links-downloads: http://dev.solace.com/downloads/
links-pubsub-tutorial: http://dev.solace.com/get-started/java-tutorials/publish-subscribe_java/
links-tls-client: http://docs.solace.com/Solace-Messaging-APIs/Creating-Secure-Sessions.htm
links-tls-server: https://docs.pivotal.io/solace-messaging/installing.html#configure
links-ldap-settings: https://docs.pivotal.io/solace-messaging/installing.html#optional_ldap_settings
links-ldap-management-settings: https://docs.pivotal.io/solace-messaging/installing.html#optional_management_access
links-client-ldap-authorization: http://docs.solace.com/Configuring-and-Managing-Routers/Configuring-LDAP-Groups.htm
links-vcap: http://docs.pivotal.io/solace-messaging/credentials.html
links-configuring-connection: http://docs.solace.com/Solace-Messaging-APIs/Configuring-Connection-T.htm
links-best-practices: http://docs.solace.com/Solace-Messaging-APIs/Best-Practices.htm
links-cf-cli: https://docs.cloudfoundry.org/cf-cli/ 
links-mqtt-pubsub-tutorial: http://dev.solace.com/get-started/mqtt-tutorials/publish-subscribe_mqtt/
links-service-instances: http://docs.pivotal.io/solace-messaging/service-instances.html
links-service-keys: http://docs.pivotal.io/solace-messaging/service-keys.html
links-installing: http://docs.pivotal.io/solace-messaging/installing.html
links-installing-tcp-routes: http://docs.pivotal.io/solace-messaging/installing.html#optional_tcp_routes
links-credentials-servicekey-example: http://docs.pivotal.io/solace-messaging/credentials.html#servicekey-example

#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
